
package cn.conon.jse.sample.websers.ws.client.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "www.conon.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param arg0
     * @return
     *     returns cn.conon.jse.sample.websers.ws.client.wsimport.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "www.conon.cn", className = "cn.conon.jse.sample.websers.ws.client.wsimport.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "www.conon.cn", className = "cn.conon.jse.sample.websers.ws.client.wsimport.GetUserByIdResponse")
    @Action(input = "www.conon.cn/HelloService/getUserByIdRequest", output = "www.conon.cn/HelloService/getUserByIdResponse")
    public User getUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param date
     */
    @WebMethod
    @RequestWrapper(localName = "getDate", targetNamespace = "www.conon.cn", className = "cn.conon.jse.sample.websers.ws.client.wsimport.GetDate")
    @ResponseWrapper(localName = "getDateResponse", targetNamespace = "www.conon.cn", className = "cn.conon.jse.sample.websers.ws.client.wsimport.GetDateResponse")
    @Action(input = "www.conon.cn/HelloService/getDateRequest", output = "www.conon.cn/HelloService/getDateResponse")
    public void getDate(
        @WebParam(name = "date", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> date);

}
